// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0-rc.1.devel
// 	protoc        v3.11.4
// source: github.com/afking/starlarkproto/testpb/star.proto

package testpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Enum int32

const (
	Enum_ENUM_A Enum = 0
	Enum_ENUM_B Enum = 1
)

// Enum value maps for Enum.
var (
	Enum_name = map[int32]string{
		0: "ENUM_A",
		1: "ENUM_B",
	}
	Enum_value = map[string]int32{
		"ENUM_A": 0,
		"ENUM_B": 1,
	}
)

func (x Enum) Enum() *Enum {
	p := new(Enum)
	*p = x
	return p
}

func (x Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_afking_starlarkproto_testpb_star_proto_enumTypes[0].Descriptor()
}

func (Enum) Type() protoreflect.EnumType {
	return &file_github_com_afking_starlarkproto_testpb_star_proto_enumTypes[0]
}

func (x Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enum.Descriptor instead.
func (Enum) EnumDescriptor() ([]byte, []int) {
	return file_github_com_afking_starlarkproto_testpb_star_proto_rawDescGZIP(), []int{0}
}

type Message_Type int32

const (
	Message_UNKNOWN  Message_Type = 0
	Message_GREETING Message_Type = 1
)

// Enum value maps for Message_Type.
var (
	Message_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "GREETING",
	}
	Message_Type_value = map[string]int32{
		"UNKNOWN":  0,
		"GREETING": 1,
	}
)

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}

func (x Message_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_afking_starlarkproto_testpb_star_proto_enumTypes[1].Descriptor()
}

func (Message_Type) Type() protoreflect.EnumType {
	return &file_github_com_afking_starlarkproto_testpb_star_proto_enumTypes[1]
}

func (x Message_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Type.Descriptor instead.
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return file_github_com_afking_starlarkproto_testpb_star_proto_rawDescGZIP(), []int{0, 0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body    string              `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Type    Message_Type        `protobuf:"varint,2,opt,name=type,proto3,enum=starlarkproto.test.Message_Type" json:"type,omitempty"`
	Strings []string            `protobuf:"bytes,3,rep,name=strings,proto3" json:"strings,omitempty"`
	Nested  *Message            `protobuf:"bytes,4,opt,name=nested,proto3" json:"nested,omitempty"`
	Maps    map[string]*Message `protobuf:"bytes,5,rep,name=maps,proto3" json:"maps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_afking_starlarkproto_testpb_star_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_afking_starlarkproto_testpb_star_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_github_com_afking_starlarkproto_testpb_star_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Message) GetType() Message_Type {
	if x != nil {
		return x.Type
	}
	return Message_UNKNOWN
}

func (x *Message) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *Message) GetNested() *Message {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Message) GetMaps() map[string]*Message {
	if x != nil {
		return x.Maps
	}
	return nil
}

var File_github_com_afking_starlarkproto_testpb_star_proto protoreflect.FileDescriptor

var file_github_com_afking_starlarkproto_testpb_star_proto_rawDesc = []byte{
	0x0a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x66, 0x6b,
	0x69, 0x6e, 0x67, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x22, 0xd6, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x33, 0x0a, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61,
	0x72, 0x6b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x04,
	0x6d, 0x61, 0x70, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x74, 0x61,
	0x72, 0x6c, 0x61, 0x72, 0x6b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x6d, 0x61, 0x70, 0x73, 0x1a, 0x54, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x21, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x52, 0x45, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x2a, 0x1e, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x4e, 0x55, 0x4d,
	0x5f, 0x41, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x42, 0x10, 0x01,
	0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x66, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_github_com_afking_starlarkproto_testpb_star_proto_rawDescOnce sync.Once
	file_github_com_afking_starlarkproto_testpb_star_proto_rawDescData = file_github_com_afking_starlarkproto_testpb_star_proto_rawDesc
)

func file_github_com_afking_starlarkproto_testpb_star_proto_rawDescGZIP() []byte {
	file_github_com_afking_starlarkproto_testpb_star_proto_rawDescOnce.Do(func() {
		file_github_com_afking_starlarkproto_testpb_star_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_afking_starlarkproto_testpb_star_proto_rawDescData)
	})
	return file_github_com_afking_starlarkproto_testpb_star_proto_rawDescData
}

var file_github_com_afking_starlarkproto_testpb_star_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_afking_starlarkproto_testpb_star_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_afking_starlarkproto_testpb_star_proto_goTypes = []interface{}{
	(Enum)(0),         // 0: starlarkproto.test.Enum
	(Message_Type)(0), // 1: starlarkproto.test.Message.Type
	(*Message)(nil),   // 2: starlarkproto.test.Message
	nil,               // 3: starlarkproto.test.Message.MapsEntry
}
var file_github_com_afking_starlarkproto_testpb_star_proto_depIdxs = []int32{
	1, // 0: starlarkproto.test.Message.type:type_name -> starlarkproto.test.Message.Type
	2, // 1: starlarkproto.test.Message.nested:type_name -> starlarkproto.test.Message
	3, // 2: starlarkproto.test.Message.maps:type_name -> starlarkproto.test.Message.MapsEntry
	2, // 3: starlarkproto.test.Message.MapsEntry.value:type_name -> starlarkproto.test.Message
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_github_com_afking_starlarkproto_testpb_star_proto_init() }
func file_github_com_afking_starlarkproto_testpb_star_proto_init() {
	if File_github_com_afking_starlarkproto_testpb_star_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_afking_starlarkproto_testpb_star_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_afking_starlarkproto_testpb_star_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_afking_starlarkproto_testpb_star_proto_goTypes,
		DependencyIndexes: file_github_com_afking_starlarkproto_testpb_star_proto_depIdxs,
		EnumInfos:         file_github_com_afking_starlarkproto_testpb_star_proto_enumTypes,
		MessageInfos:      file_github_com_afking_starlarkproto_testpb_star_proto_msgTypes,
	}.Build()
	File_github_com_afking_starlarkproto_testpb_star_proto = out.File
	file_github_com_afking_starlarkproto_testpb_star_proto_rawDesc = nil
	file_github_com_afking_starlarkproto_testpb_star_proto_goTypes = nil
	file_github_com_afking_starlarkproto_testpb_star_proto_depIdxs = nil
}
